name: "Main: Push"

on:
  pull_request:
    branches:
      - main

jobs:
  run_code_quality_and_tests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2

      - name: "Build and Verify the Code"
        run: ./scripts/ci ./scripts/build-and-verify-code
